server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  thymeleaf:
    cache: 'false'

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/his_voice

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management/actuator

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG