server:
  tomcat:
    uri-encoding: UTF-8
    mbeanregistry:
          enabled: true

spring:
  profiles:
    active: prod
    group:
      local: local, ai
      beta: real, real-port, ai, management
      prod1: real, real-prod1, ai, management
      prod2: real, real-prod2, ai, management

  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy