server:
  tomcat:
    uri-encoding: UTF-8
    mbeanregistry:
          enabled: true

spring:
  profiles:
    active: prod
    group:
      local: local, ai
      prod: real, real-port, ai, management
      set1: real, real-set1, ai, management
      set2: real, real-set2, ai, management

  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy