server:
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod
    group:
      local: local, ai
      prod: real, ai

  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy