server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    mbeanregistry:
          enabled: true

spring:
  profiles:
    group:
      local: local, ai
      beta: real, ai, management
      prod1: real, ai, management
      prod2: real, ai, management

  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy