server:
  tomcat:
    uri-encoding: UTF-8
    mbeanregistry:
          enabled: true

spring:
  profiles:
    group:
      local: local, ai
      beta: real, beta-port, ai, management
      prod1: real, prod1-port, ai, management
      prod2: real, prod2-port, ai, management

  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy